version: 1
validation: sovereign
accounts:
  - name: alice
    coins:
      - 200000000loan
  - name: bob
    coins:
      - 100000000loan
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
    - 100000loan
validators:
  - name: alice
    bonded: 100000000loan
genesis:
  app_state:
    staking:
      params:
        bond_denom: "loan"
