swagger: '2.0'
info:
  title: HTTP API Console loan.loan
  name: ''
  description: ''
paths:
  /loan/loan/loan:
    get:
      operationId: Query_LoanAll
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              Loan:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uint64
                    amount:
                      type: string
                    fee:
                      type: string
                    collateral:
                      type: string
                    deadline:
                      type: string
                    state:
                      type: string
                    borrower:
                      type: string
                    lender:
                      type: string
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /loan/loan/loan/{id}:
    get:
      operationId: Query_Loan
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              Loan:
                type: object
                properties:
                  id:
                    type: string
                    format: uint64
                  amount:
                    type: string
                  fee:
                    type: string
                  collateral:
                    type: string
                  deadline:
                    type: string
                  state:
                    type: string
                  borrower:
                    type: string
                  lender:
                    type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: uint64
      tags:
        - Query
  /loan/loan/params:
    get:
      operationId: Query_Params
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
  PageRequest:
    type: object
    properties:
      key:
        type: string
        format: byte
      offset:
        type: string
        format: uint64
      limit:
        type: string
        format: uint64
      count_total:
        type: boolean
      reverse:
        type: boolean
  PageResponse:
    type: object
    properties:
      next_key:
        type: string
        format: byte
      total:
        type: string
        format: uint64
  QueryAllLoanResponse:
    type: object
    properties:
      Loan:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              format: uint64
            amount:
              type: string
            fee:
              type: string
            collateral:
              type: string
            deadline:
              type: string
            state:
              type: string
            borrower:
              type: string
            lender:
              type: string
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
  QueryGetLoanResponse:
    type: object
    properties:
      Loan:
        type: object
        properties:
          id:
            type: string
            format: uint64
          amount:
            type: string
          fee:
            type: string
          collateral:
            type: string
          deadline:
            type: string
          state:
            type: string
          borrower:
            type: string
          lender:
            type: string
  QueryParamsResponse:
    type: object
    properties:
      params:
        type: object
  loan.Loan:
    type: object
    properties:
      id:
        type: string
        format: uint64
      amount:
        type: string
      fee:
        type: string
      collateral:
        type: string
      deadline:
        type: string
      state:
        type: string
      borrower:
        type: string
      lender:
        type: string
  loan.Params:
    type: object
  MsgUpdateParamsResponse:
    type: object
  Params:
    type: object
